// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package webviewer.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetFileId extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __inputFile;
	private webviewer.proxies.File inputFile;

	public GetFileId(IContext context, IMendixObject inputFile)
	{
		super(context);
		this.__inputFile = inputFile;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.inputFile = this.__inputFile == null ? null : webviewer.proxies.File.initialize(getContext(), __inputFile);

		// BEGIN USER CODE
		return "" + this.inputFile.getMendixObject().getId().toLong();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetFileId";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
