// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package webviewer.actions;

import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SaveDocument extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __fileData;
	private webviewer.proxies.File fileData;

	public SaveDocument(IContext context, IMendixObject fileData)
	{
		super(context);
		this.__fileData = fileData;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.fileData = this.__fileData == null ? null : webviewer.proxies.File.initialize(getContext(), __fileData);

		// BEGIN USER CODE
		// Get the file data we got from the request to write into the original object
		InputStream stream = Core.getFileDocumentContent(getContext(), this.fileData.getMendixObject());
		Core.storeFileDocumentContent(getContext(), __fileData, stream);
		// Create the new file object
		this.fileData.commit();

		// With the file ID we got from the request, create an identifier object
		IMendixIdentifier id = this.fileData.getMendixObject().getId();

		return String.valueOf(id.toLong());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SaveDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
